## Get list of tickets
GET http://localhost:3001/api/tickets HTTP/1.1
###

##
GET http://localhost:3001/api/tickets/2 HTTP/1.1
###

## Create a ticket
POST http://localhost:3001/api/tickets/ HTTP/1.1
content-type: application/json

{
    "category": "inquiry",
    "title": "This is a Title",
    "text": "This is the text of the ticket"
}
###

## Create additional content for a ticket
POST http://localhost:3001/api/tickets/40 HTTP/1.1
content-type: application/json

{
    "text": "This is the text of the ticket"
}
###

## Set status of a ticket as open
PUT http://localhost:3001/api/tickets/2/open HTTP/1.1
###

## Set status of a ticket as closed
PUT http://localhost:3001/api/tickets/3/close HTTP/1.1
###

## Update the category of a ticket
PUT http://localhost:3001/api/tickets/1/category HTTP/1.1
content-type: application/json

{
    "category": "new feature"
}
###

## Authenticate a user
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "admin1",
    "password": "passwd1"
}
###

## Delete current session
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###
